version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_DATABASE: "pin_store"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5671:5672"
      - "8082:15672"
